# Generated by Django 3.1.4 on 2020-12-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_stars',
            field=models.IntegerField(default=2),
        ),
    ]
